repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict

